export const Alumni = [
    {
        id: `alumni_1`,
        name: "Aryan Verma",
        position: "alumni",
        passout_year: 2022,
        email: "aryanvermaiit@gmail.com",
        linkedin: "https://www.linkedin.com/in/aryan-verma-98a842178",
        github: "https://github.com/Aryan-Verma",
        image: require(`../../../public/images/Alumni/Aryan Verma.jpeg`),
    },
    {
        id: `alumni_2`,
        name: "Siddhesh Shelke",
        position: "alumni",
        passout_year: 2023,
        email: "siddheshshelke015@gmail.com",
        linkedin: "www.linkedin.com/in/siddhesh-shelke/",
        github: "https://github.com/sids-09",
        image: require(`../../../public/images/Alumni/Siddhesh Shelke.jpeg`),
    },
    {
        id: `alumni_3`,
        name: "Aryan Rastogi",
        position: "alumni",
        passout_year: 2023,
        email: "aryan.rastogi13@gmail.com",
        linkedin: "www.linkedin.com/in/aryan-r22",
        github: "http://www.github.com/aryan-r22",
        image: require(`../../../public/images/Alumni/Aryan Rastogi.jpeg`),
    },

    {
        id: `alumni_4`,
        name: "Tarun Gupta",
        position: "alumni",
        passout_year: 2022,
        email: "tarungupta360@gmail.co",
        linkedin: "https://www.linkedin.com/in/tarun-gupta-116860178/",
        github: "https://github.com/tarun360",
        image: require(`../../../public/images/Alumni/Tarun Gupta.jpeg`),
    },
    {
        id: `alumni_5`,
        name: "Bharat Gupta",
        position: "alumni",
        passout_year: 2023,
        email: "bharatgupta18001@gmail.com",
        linkedin: "https://www.linkedin.com/in/bharatkgupta",
        github: "https://github.com/Bharatkgupta",
        image: require(`../../../public/images/Alumni/Bharat Gupta.jpeg`),
    },
    {
        id: `alumni_9`,
        name: "Yatharth Gupta",
        position: "Alumni",
        branch: "CSE",
        passout_year: 2025,
        email: "yatharth1.g@gmail.com",
        linkedin: "https://www.linkedin.com/in/yatharth-g/",
        github: "https://github.com/Warlord-K",
        image: require(`../../../public/images/Alumni/Yatharth Gupta.jpg`),
    },
    ,
    {
        id: `alumni_6`,
        name: "Rupal Shah",
        position: "Alumni",
        branch: "EE",
        passout_year: 2025,
        email: "ee210002065@iiti.ac.in",
        linkedin: "Linkedin.com/in/rupal17shah",
        github: "Github.com/rupal17shah",
        image: require("../../../public/images/Alumni/Rupal Shah.jpg")
    },
    {
        id: `alumni_7`,
        name: "Krish Agrawal",
        position: "Alumni",
        passout_year: 2025,
        branch: "Computer Science and Engineering",
        email: "cse210001034@iiti.ac.in",
        linkedin: "https://www.linkedin.com/in/krishagr",
        github: "https://github.com/Krish2208",
        image: require("../../../public/images/Alumni/Krish Agrawal.jpg")
    },
    {
        id: `alumni_8`,
        name: "Samip Shah",
        position: "Alumini ",
        passout_year: 2025,
        branch: "CSE",
        email: "samip.carrers@gmail.com",
        linkedin: "https://www.linkedin.com/in/samip-shah-b8435b243?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/snarkyidiot",
        image: require("../../../public/images/Alumni/Samip Shah.jpg")
    },

];